---
title: "Impact of resistance exercise training on splicing efficiency"
format: gfm
editor: visual
title-block-style: plain
---

## Introduction

This study is aimed at investigating the impact of age and resistance exercise training (RT) on splicing efficiency (SE) of introns in skeletal muscle . Using SpliceQ @demelocosta2021 we quantify the splicing efficiency of introns in RNA sequence data from six RT intervention studies;

the [COPD study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8261934/) ,

[Volume study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7708234/) ,

[ContraTrain study](https://clinicaltrials.gov/study/NCT03795025) ,

[Alpha and Omega study](https://clinicaltrials.gov/study/NCT04279951) ,

[ReLiEf study](https://www.inn.no/english/research/research-projects/relief/)

and

[SRP102542](https://pubmed.ncbi.nlm.nih.gov/28273480/)

## Repository Organisation

-   `/R`This contains the following sub-folders and scripts with codes usedin the data analyses.

    1.  `/Data_extraction` A folder containing six different R scripts that shows the extraction of the data from the different RT studies . The scripts are named to match their corresponding RT intervention studies.

    2.  `/archive` Old scripts used but not wished to be discarded

    3.  `data_compilation.R` . This extracts the individual splicing data and metadata and then merges them into one dataset ready for modelling

    4.  `model_building.R` . This uses seqwrap to build the model

    5.  `model_exploration.qmd` This script explores the built model and generates the images used in the script

    6.  `/archive/Data_exploration.R` Basic exploration of the old intron retention data . This was used before SpliceQ splice junction strigency was reduced to 5. The gene annotation used in the analysis was generated in this script

    7.  `Trainome_functions.R` Functions created for use in this study or other TrainOme studies

    8.  `beta-reg-sim-notes.qmd` Codes used in model simulation

-   `/public_data` Contains the files/documents/articles of publicly available data used or previously intended to be used in the study

-   `/resources` Contains the reference library, csl, and template used for the manuscript

-   `Relief_sampleIDs.xlsx` Annotation of relief samples/participants.

-   `Alpha_Omega_sample_list_transcriptomics.xlsx`

## Reproducing the analysis

To reproduce the analysis from scratch request access to the folder containing the raw SpliceQ counts, the run the scripts in the following order

-   `/Data_extraction`

    ## Else

    Reproduce using the already extracted SpliceQ and metadata files in the `data/` folder and run the following scripts in the order they appear

-   `data_compilation.R`

-   `model_building.R` .

-   `model_exploration.qmd`
