---
title: "Impact of age and exercise on intron retention"
format:
  docx:
    reference-doc: custom_reference.docx
author:
  - "Chidimma Phoebe Echebiri^a,b^, Kristian Lian^b^, H&aring;vard Hamarsland^b^, Knut Sindre M&#248;lmen^b^, Rafi Ahmad^a^, Stian Ellefsen^b^, and Daniel Hammarstr&ouml;m^b^"
editor: visual
csl: rna.csl
bibliography: My_Library.bib
target_journal: https://rnajournal.cshlp.org/site/misc/about.xhtml 
prefer-html: true
---

```{r, setup, include=FALSE}
getwd()

knitr::opts_knit$set(root.dir = "C:/projects/Impact-of-age-and-exercise-on-intron-retention/")
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

```

## Abstract

We profiled the skeletal muscle transcriptome of young and old individuals and observed a relative increase in IR in aged individuals. We further explored the impact of RT on IR . Genes with differential IR belonged to ontologies ...... and exhibited ..... differential expression levels. We found .... differentially retained introns in young versus old at baseline. These were contained in ....... genes.

## Introduction

Alternative splicing is a mechanism in mRNA processing in which protein-coding and non-protein coding parts of the RNA are alternatively skipped. Alternative splicing is said to regulate life and death decisions @schwerk2005 as it results in transcriptomic and proteomic diversity that could regulate different mechanisms . There are three broad types of alternative splicing; exon skipping, alternative use of splice sites, and intron retention [@nishida2015; @zheng2020 ]. Intron retention (IR) occurs when a full intron, or parts of an intron in a mature messenger RNA (mRNA)(mRNA) is retained during splicing, resulting in the presence of an unprocessed sequence in the mRNA. It affects about 80% of human protein-coding genes [@middleton2017; @braunschweig2014] .IR could either lead to the degradation of the IR-containing transcripts through nonsense-mediated decay or the action of nucleases; or it could lead to frameshifts that cause the generation of alternative protein isoforms[@baralle2023, @zheng2020, @mauger2016, @wong2022; @monteuuis2019] . IR is a physiological mechanism that controls gene expression @wong2013 . IR occurs mostly at the 3\` end of transcripts [@wong2013; @braunschweig2014]. mRNAs with retained introns play roles in normal physiology and in disease conditions @wong_intron_2016.

High IR levels correlate with downregulation of correctly spliced mRNA transcripts and low levels of protein expression @wong2013, moreso those that lack physiological relevance in cells or tissues they are detected in @braunschweig2014

Intron retention events increase with aging @mariotti_deterioration_2022

Splicing accuracy is likely under-estimated @garcía-ruiz

It is a potential biomarker or driver of the aging process [@baralle2023 ; @adusumalli_increased_2019 ].

#### Aging

Tissues and organs are altered differently by aging and aging-related processes @baralle2023.

Splicing efficiency for individual introns is cell and tissue specific @nishida2015 differential splicing efficiency . As an individual ages, mis-splicing increases @garcía-ruiz

Short genes with high mRNA levels tend to be inefficiently spliced compared to long genes with low mRNA levels. IE, there is a positive correlaation between gene length ans SE @sánchez-escabias2022. Splicing efficiency of introns in the same gene have a lower variance than when compared to introns in different genes @sánchez-escabias2022. This suggests that a fair study of intron retention should be comparing same introns in same genes across the subjects of interest. Aging and aging-like phenotypes are associated with splicing alterations [@angarola2021, @garcía-ruiz, @nishida2015, @mariotti_deterioration_2022]

Exercise is said to be an anti-aging intervention targeted at maintaining not just muscle health, but general well-being

Eukaryotes are said to have two distinct pre-mRNA splicing machinery; the major spliceosome and the minor spliceosome . The major spliceosome is said to remove over 99% of introns while the minor spliceosome removes evolutionarily conserved introns @inoue2021

R used to be considered a result of mis-splicing which render transcripts non-functional @wong_intron_2016 but is increasingly being viewed as a mechanism of gene regulation. IR is deregulated in disease conditions @ge2014

Poor splicing efficiency is related to human diseases like alpha thalassemia @nelson2005 , inflammatory bowel disease @häsler2011 , and the risk of certain cancers [@dvinge2015; @inoue2021, @shah2022]

IR could serve as biomarkers for neurodegenerative diseases @sznajder2018, and various cancers [@dvinge2015, @inoue2021]

IR could occur in response to specific developmental cues and serve as a strategy for rapid mobilization of some mRNAs for protein translation @ong2020

missplicing occurs more in non-protein coding genes than in protein-coding genes @garcía-ruiz

@won

Alternative splicing is a mechanism through which messenger RNA transcripts encode different proteins . This leads to the huge proteomic diversity seen among all living beings. @angarola2021

IR increases with age and disease conditions, it also varies across tissues and organs [@ong2020; @mariotti_deterioration_2022; @garcía-ruiz]

advancing age goes with decrease in muscle strength @frontera_aging_2000

Age is said to be positively correlated with missplicing [@garcía-ruiz; @pabis2024]

Aging is associated with the induction of different stress response pathways in different cell, tissue and specie types @stegeman2017 30 percent of alternative splicing changes in an organism occur during the aging process which is likely due to a decline in the expression of splicing factors @stegeman2017 Certain genes are said to be more prone to intron retention @stegeman2017 . Splicing damage increases with age and incidence of diseases [@mariotti_deterioration_2022 ; @stegeman2017]. The effects of retained introns could be varied depending on protein coding ability of the transcript

splicing effiociency of 0.99 might as well be several nucleotides unspliced

if aging is associated with decline in splicing efficiency, activities that improve splicing efficiency are potential targets of extending healthy lifespan and improving qualiry of life.

Aging is the progressive transformation of young organisms into aged ones. It involves changes across several physiological processes and is characterised by a progressive decline in most biological functions, and results to reduced vitality, increased risk of diseases and eventually death [@keshavarz2023; @gyenis_genome-wide_2023] . It is the greatest cause of disease and death worldwide @schaum_ageing_2020 . Aging and its processes can be targeted with therapeutics and measures aimed at slowing it down.

The concept of the "biological clock" is organ, system and sex specific @nie2022

The hallmarks of aging are said to include genomic instability, telomere attrition, epigenetic alterations, loss of prosteostatsis, dysregulated nutrient sensing, mitochondrial dysfunction, cellular senescence, stem cell exhaustion, and altered intercellular communication @lópez-otín2013

Monitoring IR in *vastula lateralis* in young and old and how they are impacted by RT could offer valuable insights into not just how age affects IR, but how RT could impact it too

Available literature suggests that intron retention increases with age

### Research questions

We hypothesize that intron retention is a mechanism by which the cells modify gene expression in response to muscular stress

Is intron retention different in old versus young?

What impact does RT have on that phenomenon

what genes are particularly more retained and more spliced out in young versus adults

Any enrichment of specific gene ontologies?

## Materials and methods

Four datasets were included in the study. Three datasets were from the TrainOme group and had either young, or old individuals. A publicly available dataset from @robinson2017 was obtained which fitted the criteria of paired-end Illumina RNA-Seq data from vastus lateralis muscle of human subjects . It contained both young and old participants.

+--------------+------------------------+-------------------+----------------------+----------------------+
| Dataset name | Number of participants | Number of samples | Age range (in years) | Linked Publication   |
+==============+========================+===================+======================+======================+
| COPD         | 53                     | 65                | 56-79                | @molmen_chronic_2021 |
+--------------+------------------------+-------------------+----------------------+----------------------+
| Volume       | 25                     | 50                | 20-37                | @khan_increased_2020 |
+--------------+------------------------+-------------------+----------------------+----------------------+
| Contratrain  | 26                     |                   | 19-34                | Hamarsland et al     |
+--------------+------------------------+-------------------+----------------------+----------------------+
| SRP102542    | 52                     | 52                | 19-30 (Young cohort) | @robinson2017        |
|              |                        |                   |                      |                      |
|              |                        |                   | 65-78 (Old cohort)   |                      |
+--------------+------------------------+-------------------+----------------------+----------------------+

Volume dataset @khan_increased_2020

COPD dataset @molmen_chronic_2021 subjects aged

Splice-Q @demelocosta2021 was used to quantify splicing efficiency. Default seetings were used where there has to be a minimum of 10 reads spanning each splice junstion.

The benjamin and hochberg method @benjamini1995 was used to control for false discovery rates

### Methodogy

Using preexercise data alone, we sought to identify differentially spliced introns by age, sex and age group. For this, we built two generalalised linear mixed beta regression models. One captured age as a continous variable and modeled the interaction between age and sex as fixed effects, while study and participant were used as random effect having individual intercepts

The second model, used age as a categorical variable where the participants were grouped into young, and old. Similar to the first model, the interaction of age_group and sex was used as fixed effects,

The differentially spliced introns based on age of preexercise data was filtered for adjusted pvalues at or below 0.05. Those that had an absolute log2fc of 1 were also filtered to determine those with significant differential expression

# Results

To investigate the impact of age and RT on intron retention, we investigated intron retention in RNA sequence data from vastus lateralis of 141 individuals from four different RT studies . The participants were divided into two age groups with young comprising 65 individuals aged between 19 to 37 , the old age group consisted of 76 participants aged between 57 and 79 .

We measured intron retention as splicing efficiency using SpliceQ @demelocosta2021. The tool

detect differentially spliced introns between young and old participants, At baseline, using the filter characteristics of adjusted p.values =\< 0.05, only age had differentially spliced introns, sex and interaction between sex and age showed no ds introns. age alone revealed 1787 out of 18541 introns were differentially spliced between old and young participants. When this data was further queried to detected those with absolute log2fc of 1, it showed that 511 were significantly spliced differently between old and young participants. 3 introns were differentially sploiced by sex

Seven introns were shown to be differentially expressed by age when used as a continous variable

Of the 1693 ds introns captured in the full dataset, 135 were changed postexercise. Based on the Estimate values, they were all improvements

## Discussion

### Shortcoming

This study did not group RT into conditions of volume of exercise done. The benefits of RT are known to be volume-dependent and the 4 studies involved varying RT conditions
